### ISSUE TITLE
Foreman Breaks When Graphite is Down While Using this Plugin

### ISSUE THREAD

**Issue by discreet** [theforeman/foreman_graphite#7]
I recently had an issue where my Graphite instance was down for maintenance. While Graphite was down The Foreman webUI was not loading properly. Once I removed the gem for the foreman_graphite plugin the webUI started working. When Graphite came back up I reinstalled the gem and everything worked fine.

**Comment by domcleal** [comment]
I think this was just fixed through issue #4 in foreman_graphite 0.0.3 (packages following soon).
